# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ankur અંકુર Patel"
description: > # this means to ignore newlines until "email:"
  Full Stack Ruby on Rails, Frontend Web and native iOS App Developer | Author of "Hands-on Full-Stack Development with Swift" amazon.com/author/ankurpatel

email: ankur.patel@ymail.com
#blog logo
logo: "/assets/images/author.png"
float_logo: true # true, false (default)

markdown: kramdown
kramdown:
  input: GFM

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Ankur Patel'
author: 'Ankur Patel'
author_image: "/assets/images/author.png"

paginate:	5

url: "https://blog.encoredevlabs.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@AnkurPatel'

#fill in disqus shortname to use disqus
disqus: encoredevlabs

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/AnkurPatel
    desc: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/ankurp
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:
